# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

do_rgig1 <- function(lambda, chi, psi) {
    .Call('_tsbcf_do_rgig1', PACKAGE = 'tsbcf', lambda, chi, psi)
}

gig_norm <- function(lambda, chi, psi) {
    .Call('_tsbcf_gig_norm', PACKAGE = 'tsbcf', lambda, chi, psi)
}

checkFit <- function(y, mcmcdraws, binary_response, doWaic, sig = NULL, yobs = NULL) {
    .Call('_tsbcf_checkFit', PACKAGE = 'tsbcf', y, mcmcdraws, binary_response, doWaic, sig, yobs)
}

dmixnorm0 <- function(x, logprob, mu, sd) {
    .Call('_tsbcf_dmixnorm0', PACKAGE = 'tsbcf', x, logprob, mu, sd)
}

pmixnorm0 <- function(x, logprob, mu, sd) {
    .Call('_tsbcf_pmixnorm0', PACKAGE = 'tsbcf', x, logprob, mu, sd)
}

dmixnorm <- function(x, logprob, mu, sd) {
    .Call('_tsbcf_dmixnorm', PACKAGE = 'tsbcf', x, logprob, mu, sd)
}

pmixnorm <- function(x, logprob, mu, sd) {
    .Call('_tsbcf_pmixnorm', PACKAGE = 'tsbcf', x, logprob, mu, sd)
}

dmixnorm0_post <- function(x, mus, sd, logprobs) {
    .Call('_tsbcf_dmixnorm0_post', PACKAGE = 'tsbcf', x, mus, sd, logprobs)
}

pmixnorm0_post <- function(x, mus, sd, logprobs) {
    .Call('_tsbcf_pmixnorm0_post', PACKAGE = 'tsbcf', x, mus, sd, logprobs)
}

dmixnorm_post <- function(x, mus, sds, logprobs) {
    .Call('_tsbcf_dmixnorm_post', PACKAGE = 'tsbcf', x, mus, sds, logprobs)
}

pmixnorm_post <- function(x, mus, sds, logprobs) {
    .Call('_tsbcf_pmixnorm_post', PACKAGE = 'tsbcf', x, mus, sds, logprobs)
}

rpgmix <- function(n, a, m) {
    .Call('_tsbcf_rpgmix', PACKAGE = 'tsbcf', n, a, m)
}

drawleft <- function(tprime) {
    .Call('_tsbcf_drawleft', PACKAGE = 'tsbcf', tprime)
}

drawright <- function(trunc) {
    .Call('_tsbcf_drawright', PACKAGE = 'tsbcf', trunc)
}

rks1 <- function() {
    .Call('_tsbcf_rks1', PACKAGE = 'tsbcf')
}

rinvgauss_cpp <- function(n, mean, shape, dispersion) {
    .Call('_tsbcf_rinvgauss_cpp', PACKAGE = 'tsbcf', n, mean, shape, dispersion)
}

rks_posterior <- function(r2) {
    .Call('_tsbcf_rks_posterior', PACKAGE = 'tsbcf', r2)
}

rightmost_interval <- function(u, lambda) {
    .Call('_tsbcf_rightmost_interval', PACKAGE = 'tsbcf', u, lambda)
}

leftmost_interval <- function(u, lambda) {
    .Call('_tsbcf_leftmost_interval', PACKAGE = 'tsbcf', u, lambda)
}

tsbcfFit <- function(y, z, zpred, tgt, tpred, x_con, x_mod, xpred_con, xpred_mod, xinfo_list_con, xinfo_list_mod, trt_init, nburn, nsim, ntree_con = 200L, ntree_mod = 50L, lambda = -999, sigq = .9, sigma = -999, nu = 3, base_con = .95, power_con = 2.0, base_mod = .25, power_mod = 3.0, ecross_con = 1, ecross_mod = 1, con_sd = 1, mod_sd = 1, use_muscale = FALSE, use_tauscale = FALSE, treef_name_ = "tsbcf_trees.txt", save_trees = FALSE, silent_mode = FALSE) {
    .Call('_tsbcf_tsbcfFit', PACKAGE = 'tsbcf', y, z, zpred, tgt, tpred, x_con, x_mod, xpred_con, xpred_mod, xinfo_list_con, xinfo_list_mod, trt_init, nburn, nsim, ntree_con, ntree_mod, lambda, sigq, sigma, nu, base_con, power_con, base_mod, power_mod, ecross_con, ecross_mod, con_sd, mod_sd, use_muscale, use_tauscale, treef_name_, save_trees, silent_mode)
}

tsbcfLogit <- function(y, yobs, z, zpred, tgt, tpred, x_con, x_mod, xpred_con, xpred_mod, xinfo_list_con, xinfo_list_mod, trt_init, nburn, nsim, ntree_con = 200L, ntree_mod = 50L, lambda = -999, sigq = .9, nu = 3, offset = 0, base_con = .95, power_con = 2.0, base_mod = .25, power_mod = 3.0, ecross_con = 1, ecross_mod = 1, con_sd = 1, mod_sd = 1, use_muscale = FALSE, use_tauscale = FALSE, treef_name_ = "tsbcf_trees.txt", save_trees = FALSE, silent_mode = FALSE) {
    .Call('_tsbcf_tsbcfLogit', PACKAGE = 'tsbcf', y, yobs, z, zpred, tgt, tpred, x_con, x_mod, xpred_con, xpred_mod, xinfo_list_con, xinfo_list_mod, trt_init, nburn, nsim, ntree_con, ntree_mod, lambda, sigq, nu, offset, base_con, power_con, base_mod, power_mod, ecross_con, ecross_mod, con_sd, mod_sd, use_muscale, use_tauscale, treef_name_, save_trees, silent_mode)
}

tsbcfProbit <- function(y, yobs, z, zpred, tgt, tpred, x_con, x_mod, xpred_con, xpred_mod, xinfo_list_con, xinfo_list_mod, trt_init, nburn, nsim, ntree_con = 200L, ntree_mod = 50L, lambda = -999, sigq = .9, nu = 3, offset = 0, base_con = .95, power_con = 2.0, base_mod = .25, power_mod = 3.0, ecross_con = 1, ecross_mod = 1, con_sd = 1, mod_sd = 1, use_muscale = FALSE, use_tauscale = FALSE, treef_name_ = "tsbcf_trees.txt", save_trees = FALSE, silent_mode = FALSE) {
    .Call('_tsbcf_tsbcfProbit', PACKAGE = 'tsbcf', y, yobs, z, zpred, tgt, tpred, x_con, x_mod, xpred_con, xpred_mod, xinfo_list_con, xinfo_list_mod, trt_init, nburn, nsim, ntree_con, ntree_mod, lambda, sigq, nu, offset, base_con, power_con, base_mod, power_mod, ecross_con, ecross_mod, con_sd, mod_sd, use_muscale, use_tauscale, treef_name_, save_trees, silent_mode)
}

